title: "MedCom on FHIR"
description: "This page includes content about MedCom FHIR standards"
logo: Medcom-logo-2015.png
description: "MedCom standard based on HL7 FHIR"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal