title: "MedCom on FHIR"
logo: /assets/images/MedCom+HL7FHIR_4.png
description: "MedCom standards based on HL7 FHIR"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
version: "Version 1.0.0"
fhir_version: "FHIR®© R4"
releasenote: https://github.com/medcomdk/MedComLandingPage/releases
thisurl: https://medcomdk.github.io/MedComLandingPage/
menuurl_item1: https://medcomdk.github.io/MedComLandingPage/
menutxt_item1: MedCom FHIR®© LandingPage
menuurl_item2: https://medcomdk.github.io/MedCom-FHIR-Communication/#network-layer
menutxt_item2: MedCom FHIR®© Governance
# menuurl_item3: https://medcomdk.github.io/MedCom-FHIR-Communication/#About
# menutxt_item3: About MedCom FHIR®© Governance
